name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_push_to_docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        uses: actions/checkout@v2
      - 
        name: read version
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./version
      - 
        name: read base image version
        id: base_version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./base_image_version
      - 
        name: read docker version
        id: docker_version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./docker_version
      -
        name: Build and push latest
        id: docker_build_latest
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          push: true
          tags: sefose/fullstack-container:latest
          build-args: |
            BASE_VERSION=${{ steps.base_version.outputs.content }}
            DOCKER_VERSION=${{ steps.docker_version.outputs.content }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build_latest.outputs.digest }}
      -
        name: Build and push version
        id: docker_build_version
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          push: true
          tags: sefose/fullstack-container:${{ steps.base_version.outputs.content }}_${{ steps.version.outputs.content }}
          build-args: |
            BASE_VERSION=${{ steps.base_version.outputs.content }}
            DOCKER_VERSION=${{ steps.docker_version.outputs.content }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build_version.outputs.digest }}
